//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catagory
    {
        public Catagory()
        {
            this.PIDevices = new HashSet<PIDevice>();
            this.PIPlayQueues = new HashSet<PIPlayQueue>();
        }
    
        public int idCatagory { get; set; }
    
        public virtual ICollection<PIDevice> PIDevices { get; set; }
        public virtual Musik Musik { get; set; }
        public virtual ICollection<PIPlayQueue> PIPlayQueues { get; set; }
    }
}
