//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class device
    {
        public device()
        {
            this.filepaths = new HashSet<filepath>();
        }
    
        public string UUIDDevice { get; set; }
        public string IP { get; set; }
        public string PCOwner { get; set; }
        public string Protocol { get; set; }
    
        public virtual ICollection<filepath> filepaths { get; set; }
    }
}
