//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class filepath
    {
        public filepath()
        {
            this.musicdatas = new HashSet<musicdata>();
        }
    
        public string UUIDPath { get; set; }
        public string FilePath1 { get; set; }
        public string Device_UUIDDevice { get; set; }
    
        public virtual device device { get; set; }
        public virtual ICollection<musicdata> musicdatas { get; set; }
    }
}
