//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pcindexEntities : DbContext
    {
        public pcindexEntities()
            : base("name=pcindexEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<album> albums { get; set; }
        public DbSet<artist> artists { get; set; }
        public DbSet<device> devices { get; set; }
        public DbSet<filepath> filepaths { get; set; }
        public DbSet<genre> genres { get; set; }
        public DbSet<musicdata> musicdatas { get; set; }
    }
}
