//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PiindexEntities : DbContext
    {
        public PiindexEntities()
            : base("name=PiindexEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Catagory> Catagories { get; set; }
        public DbSet<Musik> Musiks { get; set; }
        public DbSet<PIAlbum> PIAlbums { get; set; }
        public DbSet<PIArtist> PIArtists { get; set; }
        public DbSet<PIDevice> PIDevices { get; set; }
        public DbSet<PIFilePath> PIFilePaths { get; set; }
        public DbSet<PIGenre> PIGenres { get; set; }
        public DbSet<PIMusikData> PIMusikDatas { get; set; }
        public DbSet<PIPlayQueue> PIPlayQueues { get; set; }
    }
}
