//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PIPlayQueue
    {
        public int Catagory_idCatagory { get; set; }
        public int Idnummer { get; set; }
        public string MusikData_idMusikData { get; set; }
    
        public virtual Catagory Catagory { get; set; }
        public virtual PIMusikData PIMusikData { get; set; }
    }
}
